[describe]
1=(a) describe how hydrogen bonding occurs between water molecules, and relate this, and other properties of water, to the roles of water in living organisms (HSW1);
18=(r) describe how to carry out chemical tests to identify the presence of the following molecules: protein (biuret test), reducing and non-reducing sugars (Benedict's test), starch (iodine solution) and lipids (emulsion test);
19=(s) describe how the concentration of glucose in a solution may be determined using colorimetry (HSW3).
29=(d) describe and explain the effects of pH, temperature, enzyme concentration and substrate concentration on enzyme activity;
30=(e) describe how the effects of pH, temperature, enzyme concentration and substrate concentration on enzyme activity can be investigated experimentally;
42=(h) describe how the use of fertilisers and pesticides with plants and the use of antibiotics with animals can increase food production (HSW6a, 6b);
43=(i) describe the advantages and disadvantages of using microorganisms to make food for human consumption;
47=(c) describe the causes and means of transmission of malaria, AIDS/HIV and TB (knowledge of the symptoms of these diseases is not required);
50=(f) describe the primary defences against pathogens and parasites (including skin and mucus membranes) and outline their importance. (No details of skin structure are required);
54=(j) describe the structure and mode of action of T lymphocytes and B lymphocytes, including the significance of cell signalling and the role of memory cells;
60=(p) describe the effects of smoking on the mammalian gas exchange system, with reference to the symptoms of chronic bronchitis, emphysema (chronic obstructive pulmonary disease) and lung cancer;
61=(q) describe the effects of nicotine and carbon monoxide in tobacco smoke on the cardiovascular system with reference to the course of events that lead to atherosclerosis, coronary heart disease and stroke;
66=(d) describe how random samples can be taken when measuring biodiversity;
67=(e) describe how to measure species richness and species evenness in a habitat;
73=(c) describe the classification of species into the taxonomic hierarchy of domain, kingdom, phylum, class, order, family, genus and species;
81=(c) describe the differences between continuous and discontinuous variation, using examples of a range of characteristics found in plants, animals and microorganisms;
92=(d) describe the conservation of endangered plant and animal species, both in situ and ex situ, with reference to the advantages and disadvantages of these two approaches (HSW4, 6a, 6b);
101=(f) describe the physiological and behavioural responses that maintain a constant core body temperature in ectotherms and endotherms, with reference to peripheral temperature receptors, the hypothalamus and effectors in skin and muscles.
104=(c) describe and explain how the resting potential is established and maintained;
105=(d) describe and explain how an action potential is generated;
106=(e) describe and explain how an action potential is transmitted in a myelinated neurone, with reference to the roles of voltage-gated sodium ion and potassium ion channels;
115=(c) describe the functions of the adrenal glands;
125=(d) describe the formation of urea in the liver, including an outline of the ornithine cycle;
126=(e) describe the roles of the liver in detoxification;
129=(h) describe and explain the production of urine, with reference to the processes of ultrafiltration and selective reabsorption;
132=(k) describe how urine samples can be used to test for pregnancy and detect misuse of anabolic steroids (HSW6a, 6b).
147=(o) describe the effect on the rate of photosynthesis, and on levels of GP, RuBP and TP, of changing carbon dioxide concentration, light intensity and temperature;
149=(q) describe how to investigate experimentally the factors that affect the rate of photosynthesis (HSW3).
188=(f) describe the interactions between loci (epistasis). (Production of genetic diagrams is not required);
191=(i) describe the differences between continuous and discontinuous variation;
201=(s) describe how artificial selection has been used to produce the modern dairy cow and to produce bread wheat (Triticum aestivum) (HSW6a, 6b).
203=(b) describe the production of natural clones in plants using the example of vegetative propagation in elm trees;
204=(c) describe the production of artificial clones of plants from tissue culture;
206=(e) describe how artificial clones of animals can be produced;
211=(d) describe how enzymes can be immobilised;
214=(g) describe the differences between primary and secondary metabolites;
221=(e) describe how sections of DNA containing a desired gene can be extracted from a donor organism using restriction enzymes;
223=(g) describe how DNA probes can be used to identify fragments containing specific sequences;
228=(l) describe the advantage to microorganisms of the capacity to take up plasmid DNA from the environment;
240=(e) describe how energy is transferred though ecosystems;
244=(i) describe one example of primary succession resulting in a climax community;
245=(j) describe how the distribution and abundance of organisms can be measured, using line transects, belt transects, quadrats and point quadrats (HSW3);
246=(k) describe the role of decomposers in the decomposition of organic material;
247=(l) describe how microorganisms recycle nitrogen within ecosystems. (Only Nitrosomonas, Nitrobacter and Rhizobium need to be identified by name).
250=(c) describe predator-prey relationships and their possible effects on the population sizes of both the predator and the prey;
262=(f) describe how plant hormones are used commercially (HSW6a).
267=(e) describe the role of the brain and nervous system in the co-ordination of muscular movement;
268=(f) describe how co-ordinated movement requires the action of skeletal muscles about joints, with reference to the movement of the elbow joint;
276=(b) describe escape reflexes, taxes and kineses as examples of genetically-determined innate behaviours;
278=(d) describe habituation, imprinting, classical and operant conditioning, latent and insight learning as examples of learned behaviours;
[describe,]
2=(b) describe, with the aid of diagrams, the structure of an amino acid;
3=(c) describe, with the aid of diagrams, the formation and breakage of peptide bonds in the synthesis and hydrolysis of dipeptides and polypeptides;
8=(h) describe, with the aid of diagrams, the structure of a collagen molecule;
10=(j) describe, with the aid of diagrams, the molecular structure of alpha-glucose as an example of a monosaccharide carbohydrate;
12=(l) describe, with the aid of diagrams, the formation and breakage of glycosidic bonds in the synthesis and hydrolysis of a disaccharide (maltose) and a polysaccharide (amylose);
14=(n) describe, with the aid of diagrams, the structure of glycogen;
22=(c) describe, with the aid of diagrams, how hydrogen bonding between complementary base pairs (A to T, G to C) on two antiparallel DNA polynucleotides leads to the formation of a DNA molecule, and how the twisting of DNA produces its "double-helix" shape (HSW1);
28=(c) describe, with the aid of diagrams, the mechanism of action of enzyme molecules, with reference to specificity, active site, lock and key hypothesis, induced-fit hypothesis, enzyme-substrate complex, enzyme-product complex and lowering of activation energy;
51=(g) describe, with the aid of diagrams and photographs, the structure and mode of action of phagocytes;
52=(h) describe, with the aid of diagrams, the structure of antibodies;
103=(b) describe, with the aid of diagrams, the structure and functions of sensory and motor neurones;
110=(i) describe, with the aid of diagrams, the structure of a cholinergic synapse;
116=(d) describe, with the aid of diagrams and photographs, the histology of the pancreas, and outline its role as an endocrine and exocrine gland;
124=(c) describe, with the aid of diagrams and photographs, the histology and gross structure of the liver;
127=(f) describe, with the aid of diagrams and photographs, the histology and gross structure of the kidney;
128=(g) describe, with the aid of diagrams and photographs, the detailed structure of a nephron and its associated blood vessels;
151=(b) describe, with the aid of diagrams, the structure of ATP;
175=(c) describe, with the aid of diagrams, the way in which a nucleotide sequence codes for the amino acid sequence in a polypeptide;
176=(d) describe, with the aid of diagrams, how the sequence of nucleotides within a gene is used to construct a polypeptide, including the roles of messenger RNA, transfer RNA and ribosomes;
183=(a) describe, with the aid of diagrams and photographs, the behaviour of chromosomes during meiosis, and the associated behaviour of the nuclear envelope, cell membrane and centrioles. (Names of the main stages are expected, but not the subdivisions of prophase);
210=(c) describe, with the aid of diagrams, and explain the standard growth curve of a microorganism in a closed culture;
266=(d) describe, with the aid of diagrams, the gross structure of the human brain, and outline the functions of the cerebrum, cerebellum, medulla oblongata and hypothalamus;
279=(e) describe, using one example, the advantages of social behaviour in primates;
[explain,]
4=(d) explain, with the aid of diagrams, the term primary structure;
5=(e) explain, with the aid of diagrams, the term secondary structure with reference to hydrogen bonding;
6=(f) explain, with the aid of diagrams, the term tertiary structure, with reference to hydrophobic and hydrophilic interactions, disulfide bonds and ionic interactions;
7=(g) explain, with the aid of diagrams, the term quaternary structure, with reference to the structure of haemoglobin;
130=(i) explain, using water potential terminology, the control of the water content of the blood, with reference to the roles of the kidney, osmoreceptors in the hypothalamus and the posterior pituitary gland;
137=(e) explain, with the aid of diagrams and electron micrographs, how the structure of chloroplasts enables them to carry out their functions;
157=(h) explain, with the aid of diagrams and electron micrographs, how the structure of mitochondria enables them to carry out their functions;
196=(n) explain, with examples, how environmental factors can act as stabilising or evolutionary forces of natural selection;
251=(d) explain, with examples, the terms interspecific and intraspecific competition;
269=(g) explain, with the aid of diagrams and photographs, the sliding filament model of muscular contraction;
[compare]
9=(i) compare the structure and function of haemoglobin (as an example of a globular protein) and collagen (as an example of a fibrous protein);
13=(m) compare and contrast the structure and functions of starch (amylose) and cellulose;
55=(k) compare and contrast the primary and secondary immune responses;
56=(l) compare and contrast active, passive, natural and artificial immunity;
78=(h) compare and contrast the five kingdom and three domain classification systems (HSW4, 7a, 7b).
109=(h) compare and contrast the structure and function of myelinated and non-myelinated neurones;
119=(g) compare and contrast the causes of Type 1 (insulin-dependent) and Type 2 (non-insulin-dependent) diabetes mellitus;
170=(u) compare and contrast anaerobic respiration in mammals and in yeast;
200=(r) compare and contrast natural selection and artificial selection;
213=(f) compare and contrast the processes of continuous culture and batch culture;
271=(i) compare and contrast the action of synapses and neuromuscular junctions;
[state]
11=(k) state the structural difference between alpha- and beta-glucose;
20=(a) state that deoxyribonucleic acid (DNA) is a polynucleotide, usually double stranded, made up of nucleotides containing the bases adenine (A), thymine (T), cytosine (C) and guanine (G);
21=(b) state that ribonucleic acid (RNA) is a polynucleotide, usually single stranded, made up of nucleotides containing the bases adenine (A), uracil (U), cytosine (C) and guanine (G);
24=(e) state that a gene is a sequence of DNA nucleotides that codes for a polypeptide (HSW3);
26=a) state that enzymes are globular proteins, with a specific tertiary structure, which catalyse metabolic reactions in living organisms;
27=(b) state that enzyme action may be intracellular or extracellular;
33=(h) state that metabolic poisons may be enzyme inhibitors, and describe the action of one named poison;
34=(i) state that some medicinal drugs work by inhibiting the activity of enzymes (HSW6a).
97=(b) state that cells need to communicate with each other by a process called cell signalling;
98=(c) state that neuronal and hormonal systems are examples of cell signalling;
134=(b) state that light energy is used during photosynthesis to produce complex organic molecules;
136=(d) state that in plants photosynthesis is a two-stage process taking place in chloroplasts;
140=(h) state that the light-dependent stage takes place in thylakoid membranes and that the light-independent stage takes place in the stroma;
145=(m) state that TP can be used to make carbohydrates, lipids and amino acids;
146=(n) state that most TP is recycled to RuBP;
152=(c) state that ATP provides the immediate source of energy for biological processes;
154=(e) state that glycolysis takes place in the cytoplasm;
156=(g) state that, during aerobic respiration in animals, pyruvate is actively transported into mitochondria;
158=(i) state that the link reaction takes place in the mitochondrial matrix;
161=(l) state that the Krebs cycle takes place in the mitochondrial matrix;
166=(q) state that oxygen is the final electron acceptor in aerobic respiration;
173=(a) state that genes code for polypeptides, including enzymes;
177=(e) state that mutations cause changes to the sequence of nucleotides in DNA molecules;
179=(g) state that cyclic AMP activates proteins by altering their three-dimensional structure;
208=(a) state that biotechnology is the industrial use of living organisms (or parts of living organisms) to produce food, drugs or other products (HSW6a);
226=(j) state other vectors into which fragments of DNA may be incorporated;
237=(b) state that ecosystems are dynamic systems;
273=(k) state that responses to environmental stimuli in mammals are co-ordinated by nervous and endocrine systems;
[explain]
15=(o) explain how the structures of glucose, starch (amylose), glycogen and cellulose molecules relate to their functions in living organisms;
17=(q) explain how the structures of triglyceride, phospholipid and cholesterol molecules relate to their functions in living organisms;
31=(f) explain the effects of competitive and non-competitive inhibitors on the rate of enzyme-controlled reactions, with reference to both reversible and non-reversible inhibitors;
32=(g) explain the importance of cofactors and coenzymes in enzyme-controlled reactions;
36=(b) explain how consumption of an unbalanced diet can lead to malnutrition, with reference to obesity (HSW4);
39=(e) explain that humans depend on plants for food as they are the basis of all food chains. (No details of food chains are required);
57=(m) explain how vaccination can control disease (HSW6a, 7c);
64=(b) explain how biodiversity may be considered at different levels; habitat, species and genetic;
65=(c) explain the importance of sampling in measuring the biodiversity of a habitat (HSW7a, 7b, 7c);
72=(b) explain the relationship between classification and phylogeny;
82=(d) explain both genetic and environmental causes of variation;
84=(f) explain the consequences of the four observations made by Darwin in proposing his theory of natural selection; (HSW1)
91=(c) explain the benefits for agriculture of maintaining the biodiversity of animal and plant species (HSW6a, 6b, 7c);
100=(e) explain the principles of homeostasis in terms of receptors, effectors and negative feedback;
114=(b) explain the meaning of the terms first messenger and second messenger, with reference to adrenaline and cyclic AMP (cAMP);
117=(e) explain how blood glucose concentration is regulated, with reference to insulin, glucagon and the liver;
123=(b) explain the importance of removing metabolic wastes, including carbon dioxide and nitrogenous waste, from the body;
135=(c) explain how respiration in plants and animals depends upon the products of photosynthesis;
139=(g) explain the importance of photosynthetic pigments in photosynthesis;
142=(j) explain the role of water in the light-dependent stage;
144=(l) explain the role of carbon dioxide in the light-independent stage (Calvin cycle);
153=(d) explain the importance of coenzymes in respiration, with reference to NAD and coenzyme A;
160=(k) explain that acetate is combined with coenzyme A to be carried to the next stage;
163=(n) explain that during the Krebs cycle, decarboxylation and dehydrogenation occur, NAD and FAD are reduced and substrate level phosphorylation occurs;
168=(s) explain why the theoretical maximum yield of ATP per molecule of glucose is rarely, if ever, achieved in aerobic respiration;
169=(t) explain why anaerobic respiration produces a much lower yield of ATP than aerobic respiration;
172=(w) explain the difference in relative energy values of carbohydrate, lipid and protein respiratory substrates.
174=(b) explain the meaning of the term genetic code;
178=(f) explain how mutations can have beneficial, neutral or harmful effects on the way a protein functions;
180=(h) explain genetic control of protein production in a prokaryote using the lac operon;
181=(i) explain that the genes that control development of body plans are similar in plants, animals and fungi, with reference to homeobox sequences (HSW1);
184=(b) explain the terms allele, locus, phenotype, genotype, dominant, codominant and recessive;
185=(c) explain the terms linkage and crossing-over;
186=(d) explain how meiosis and fertilisation can lead to variation through the independent assortment of alleles;
192=(j) explain the basis of continuous and discontinuous variation by reference to the number of genes which influence the variation;
193=(k) explain that both genotype and environment contribute to phenotypic variation. (No calculations of heritability will be expected);
194=(l) explain why variation is essential in selection;
197=(o) explain how genetic drift can cause large changes in small populations;
198=(p) explain the role of isolating mechanisms in the evolution of new species, with reference to ecological (geographic), seasonal (temporal) and reproductive mechanisms;
199=(q) explain the significance of the various concepts of the species, with reference to the biological species concept and the phylogenetic (cladistic/evolutionary) species concept (HSW1);
209=(b) explain why microorganisms are often used in biotechnological processes;
212=(e) explain why immobilised enzymes are used in large-scale production;
215=(h) explain the importance of manipulating the growing conditions in a fermentation vessel in order to maximise the yield of product required;
216=(i) explain the importance of asepsis in the manipulation of microorganisms.
220=(d) explain that genetic engineering involves the extraction of genes from one organism, or the manufacture of genes, in order to place them in another organism (often of a different species) such that the receiving organism expresses the gene product (HSW6a);
225=(i) explain how isolated DNA fragments can be placed in plasmids, with reference to the role of ligase;
227=(k) explain how plasmids may be taken up by bacterial cells in order to produce a transgenic microorganism that can express a desired gene product;
233=(q) explain the term gene therapy;
234=(r) explain the differences between somatic cell gene therapy and germ line cell gene therapy;
243=(h) explain how human activities can manipulate the flow of energy through ecosystems (HSW6b);
248=(a) explain the significance of limiting factors in determining the final size of a population;
249=(b) explain the meaning of the term carrying capacity;
253=(f) explain how the management of an ecosystem can provide resources in a sustainable way, with reference to timber production in a temperate country;
254=(g) explain that conservation is a dynamic process involving management and reclamation;
257=(a) explain why plants need to respond to their environment in terms of the need to avoid predation and abiotic stress;
259=(c) explain how plant responses to environmental changes are co-ordinated by hormones, with reference to responding to changes in light direction;
274=(l) explain how, in mammals, the "fight or flight" response to environmental stimuli is co-ordinated by the nervous and endocrine systems.
275=(a) explain the advantages to organisms of innate behaviour;
277=(c) explain the meaning of the term learned behaviour;
[compare,]
16=(p) compare, with the aid of diagrams, the structure of a triglyceride and a phospholipid;
[outline,]
23=(d) outline, with the aid of diagrams, how DNA replicates semi-conservatively, with reference to the role of DNA polymerase;
256=(i) outline, with examples, the effects of human activities on the animal and plant populations in the Galapagos Islands (HSW6b).
[outline]
25=(f) outline the roles of DNA and RNA in living organisms (the concept of protein synthesis must be considered in outline only).
40=(f) outline how selective breeding is used to produce crop plants with high yields, disease resistance and pest resistance (HSW6a);
41=(g) outline how selective breeding is used to produce domestic animals with high productivity (HSW6a);
44=(j) outline how salting, adding sugar, pickling, freezing, heat treatment and irradiation can be used to prevent food spoilage by microorganisms.
53=(i) outline the mode of action of antibodies, with reference to the neutralisation and agglutination of pathogens;
59=(o) outline possible new sources of medicines, with reference to microorganisms and plants and the need to maintain biodiversity (HSW 6a, 6b, 7b);
69=(g) outline the significance of both high and low values of Simpson's Index of Diversity (D);
74=(d) outline the characteristic features of the following five kingdoms: Prokaryotae (Monera), Protoctista, Fungi, Plantae, Animalia;
75=(e) outline the binomial system of nomenclature and the use of scientific (Latin) names for species;
83=(e) outline the behavioural, physiological and anatomical (structural) adaptations of organisms to their environments;
87=(i) outline how variation, adaptation and selection are major components of evolution;
89=(a) outline the reasons for the conservation of animal and plant species, with reference to economic, ecological, ethical and aesthetic reasons (HSW6b);
96=(a) outline the need for communication systems within multicellular organisms, with reference to the need to respond to changes in the internal and external environment and to co-ordinate the activities of different organs;
102=(a) outline the roles of sensory receptors in mammals in converting different forms of energy into nerve impulses;
108=(g) outline the significance of the frequency of impulse transmission;
111=(j) outline the role of neurotransmitters in the transmission of action potentials;
112=(k) outline the roles of synapses in the nervous system.
118=(f) outline how insulin secretion is controlled, with reference to potassium channels and calcium channels in beta cells;
121=(i) outline the hormonal and nervous mechanisms involved in the control of heart rate in humans.
131=(j) outline the problems that arise from kidney failure and discuss the use of renal dialysis and transplants for the treatment of kidney failure (HSW6a, 6b, 7c);
141=(i) outline how light energy is converted to chemical energy (ATP and reduced NADP) in the light-dependent stage (reference should be made to cyclic and non-cyclic photophosphorylation, but no biochemical detail is required);
143=(k) outline how the products of the light-dependent stage are used in the light-independent stage (Calvin cycle) to produce triose phosphate (TP) (reference should be made to ribulose bisphosphate (RuBP), ribulose bisphosphate carboxylase (rubisco) and glycerate 3-phosphate (GP), but no other biochemical detail is required);
150=(a) outline why plants, animals and microorganisms need to respire, with reference to active transport and metabolic reactions;
155=(f) outline the process of glycolysis beginning with the phosphorylation of glucose to hexose bisphosphate, splitting of hexose bisphosphate into two triose phosphate molecules and further oxidation to pyruvate, producing a small yield of ATP and reduced NAD;
159=(j) outline the link reaction, with reference to decarboxylation of pyruvate to acetate and the reduction of NAD;
162=(m) outline the Krebs cycle, with reference to the formation of citrate from acetate and oxaloacetate and the reconversion of citrate to oxaloacetate (names of intermediate compounds are not required);
164=(o) outline the process of oxidative phosphorylation, with reference to the roles of electron carriers, oxygen and the mitochondrial cristae;
165=(p) outline the process of chemiosmosis, with reference to the electron transport chain, proton gradients and ATPsynthase (HSW7a);
182=(j) outline how apoptosis (programmed cell death) can act as a mechanism to change body plans.
202=(a) outline the differences between reproductive and non-reproductive cloning;
217=(a) outline the steps involved in sequencing the genome of an organism;
218=(b) outline how gene sequencing allows for genome-wide comparisons between individuals and between species (HSW7b);
222=(f) outline how DNA fragments can be separated by size using electrophoresis (HSW3);
224=(h) outline how the polymerase chain reaction (PCR) can be used to make multiple copies of DNA fragments;
229=(m) outline how genetic markers in plasmids can be used to identify the bacteria that have taken up a recombinant plasmid;
230=(n) outline the process involved in the genetic engineering of bacteria to produce human insulin;
231=(o) outline the process involved in the genetic engineering of "Golden Rice"^TM (HSW6a);
232=(p) outline how animals can be genetically engineered for xenotransplantation (HSW6a, 6b);
241=(f) outline how energy transfers between trophic levels can be measured;
261=(e) outline the role of hormones in leaf loss in deciduous plants;
264=(b) outline the organisation of the nervous system in terms of central and peripheral systems in humans;
265=(c) outline the organisation and roles of the autonomic nervous system;
270=(h) outline the role of ATP in muscular contraction, and how the supply of ATP is maintained in muscles;
272=(j) outline the structural and functional differences between voluntary, involuntary and cardiac muscle;
[define]
35=(a) define the term balanced diet;
46=(b) define and discuss the meanings of the terms parasite and pathogen;
49=(e) define the terms immune response, antigen and antibody;
63=(a) define the terms species, habitat and biodiversity;
71=(a) define the terms classification, phylogeny and taxonomy;
79=(a) define the term variation;
85=(g) define the term speciation;
99=(d) define the terms negative feedback, positive feedback and homeostasis;
113=(a) define the terms endocrine gland, exocrine gland, hormone and target tissue;
122=(a) define the term excretion;
133=(a) define the terms autotroph and heterotroph;
138=(f) define the term photosynthetic pigment;
171=(v) define the term respiratory substrate;
219=(c) define the term recombinant DNA;
236=(a) define the term ecosystem;
238=(c) define the terms biotic factor and abiotic factor, using named examples;
239=(d) define the terms producer, consumer decomposer and trophic level;
258=(b) define the term tropism;
[discuss]
37=(c) discuss the possible links between diet and coronary heart disease (CHD);
38=(d) discuss the possible effects of a high blood cholesterol level on the heart and circulatory system, with reference to high-density lipoproteins (HDL) and low-density lipoprotein (LDL) (HSW1);
45=(a) discuss what is meant by the terms health and disease;
48=(d) discuss the global impact of malaria, AIDS/HIV and TB (HSW4, 6a, 7c);
58=(n) discuss the responses of governments and other organisations to the threat of new strains of influenza each year (HSW7b, 7c);
70=(h) discuss current estimates of global biodiversity (HSW7a, 7b, 7c).
77=(g) discuss the fact that classification systems were based originally on observable features but more recent approaches draw on a wider range of evidence to clarify relationships between organisms, including molecular evidence (HSW1, 7a);
80=(b) discuss the fact that variation occurs within as well as between species;
86=(h) discuss the evidence supporting the theory of evolution, with reference to fossil, DNA and molecular evidence (HSW1, 4, 7a, 7b);
88=(j) discuss why the evolution of pesticide resistance in insects and drug resistance in microorganisms has implications for humans (HSW6a, 7c).
90=(b) discuss the consequences of global climate change on the biodiversity of plants and animals, with reference to changing patterns of agriculture and spread of disease (HSW6a, 6b, 7a, 7b, 7c);
93=(e) discuss the role of botanic gardens in the ex situ conservation of rare plant species or plant species extinct in the wild, with reference to seed banks;
94=(f) discuss the importance of international co-operation in species conservation with reference to The Convention in International Trade in Endangered Species (CITES) and the Rio Convention on Biodiversity (HSW6b, 7b, 7c);
95=(g) discuss the significance of environmental impact assessments (including biodiversity estimates) for local authority planning decisions. (HSW6b, 7c).
120=(h) discuss the use of insulin produced by genetically modified bacteria, and the potential use of stem cells, to treat diabetes mellitus (HSW6a, 7b);
148=(p) discuss limiting factors in photosynthesis with reference to carbon dioxide concentration, light intensity and temperature;
205=(d) discuss the advantages and disadvantages of plant cloning in agriculture (HSW6a, 6b, 7c);
207=(f) discuss the advantages and disadvantages of cloning animals (HSW4, 6a, 6b, 7c).
235=(s) discuss the ethical concerns raised by the genetic manipulation of animals (including humans), plants and microorganisms (HSW4, 6a, 6b, 7c).
242=(g) discuss the efficiency of energy transfers between trophic levels;
255=(h) discuss the economic, social and ethical reasons for conservation of biological resources (HSW6b, 7c);
263=(a) discuss why animals need to respond to their environment;
280=(f) discuss how the links between a range of human behaviours and the dopamine receptor DRD4 may contribute to the understanding of human behaviour (HSW7a);
[evaluate]
62=(r) evaluate the epidemiological and experimental evidence linking cigarette smoking to disease and early death (HSW3, 6a, 7a, 7b, 7c).
167=(r) evaluate the experimental evidence for the theory of chemiosmosis (HSW1);
260=(d) evaluate the experimental evidence for the role of auxins in the control of apical dominance and gibberellin in the control of stem elongation;
[use]
68=(f) use Simpson's Index of Diversity (D) to calculate the biodiversity of a habitat, using the formula D = 1-(S(n/N)2) (HSW3);
76=(f) use a dichotomous key to identify a group of at least six plants, animals or microorganisms;
187=(e) use genetic diagrams to solve problems involving sex linkage and codominance;
190=(h) use the chi-squared (?2) test to test the significance of the difference between observed and expected results. (The formula for the chi-squared test will be provided);
195=(m) use the Hardy-Weinberg principle to calculate allele frequencies in populations (HSW1);
[interpret]
107=(f) interpret graphs of the voltage changes taking place during the generation and transmission of an action potential;
[predict]
189=(g) predict phenotypic ratios in problems involving epistasis;
[distinguish]
252=(e) distinguish between the terms conservation and preservation (HSW6a, 6b);
[F214]
96=(a) outline the need for communication systems within multicellular organisms, with reference to the need to respond to changes in the internal and external environment and to co-ordinate the activities of different organs;
102=(a) outline the roles of sensory receptors in mammals in converting different forms of energy into nerve impulses;
107=(f) interpret graphs of the voltage changes taking place during the generation and transmission of an action potential;
108=(g) outline the significance of the frequency of impulse transmission;
111=(j) outline the role of neurotransmitters in the transmission of action potentials;
112=(k) outline the roles of synapses in the nervous system.
118=(f) outline how insulin secretion is controlled, with reference to potassium channels and calcium channels in beta cells;
121=(i) outline the hormonal and nervous mechanisms involved in the control of heart rate in humans.
131=(j) outline the problems that arise from kidney failure and discuss the use of renal dialysis and transplants for the treatment of kidney failure (HSW6a, 6b, 7c);
141=(i) outline how light energy is converted to chemical energy (ATP and reduced NADP) in the light-dependent stage (reference should be made to cyclic and non-cyclic photophosphorylation, but no biochemical detail is required);
143=(k) outline how the products of the light-dependent stage are used in the light-independent stage (Calvin cycle) to produce triose phosphate (TP) (reference should be made to ribulose bisphosphate (RuBP), ribulose bisphosphate carboxylase (rubisco) and glycerate 3-phosphate (GP), but no other biochemical detail is required);
150=(a) outline why plants, animals and microorganisms need to respire, with reference to active transport and metabolic reactions;
155=(f) outline the process of glycolysis beginning with the phosphorylation of glucose to hexose bisphosphate, splitting of hexose bisphosphate into two triose phosphate molecules and further oxidation to pyruvate, producing a small yield of ATP and reduced NAD;
159=(j) outline the link reaction, with reference to decarboxylation of pyruvate to acetate and the reduction of NAD;
162=(m) outline the Krebs cycle, with reference to the formation of citrate from acetate and oxaloacetate and the reconversion of citrate to oxaloacetate (names of intermediate compounds are not required);
164=(o) outline the process of oxidative phosphorylation, with reference to the roles of electron carriers, oxygen and the mitochondrial cristae;
165=(p) outline the process of chemiosmosis, with reference to the electron transport chain, proton gradients and ATPsynthase (HSW7a);
167=(r) evaluate the experimental evidence for the theory of chemiosmosis (HSW1);
120=(h) discuss the use of insulin produced by genetically modified bacteria, and the potential use of stem cells, to treat diabetes mellitus (HSW6a, 7b);
148=(p) discuss limiting factors in photosynthesis with reference to carbon dioxide concentration, light intensity and temperature;
99=(d) define the terms negative feedback, positive feedback and homeostasis;
113=(a) define the terms endocrine gland, exocrine gland, hormone and target tissue;
122=(a) define the term excretion;
133=(a) define the terms autotroph and heterotroph;
138=(f) define the term photosynthetic pigment;
171=(v) define the term respiratory substrate;
101=(f) describe the physiological and behavioural responses that maintain a constant core body temperature in ectotherms and endotherms, with reference to peripheral temperature receptors, the hypothalamus and effectors in skin and muscles.
104=(c) describe and explain how the resting potential is established and maintained;
105=(d) describe and explain how an action potential is generated;
106=(e) describe and explain how an action potential is transmitted in a myelinated neurone, with reference to the roles of voltage-gated sodium ion and potassium ion channels;
115=(c) describe the functions of the adrenal glands;
125=(d) describe the formation of urea in the liver, including an outline of the ornithine cycle;
126=(e) describe the roles of the liver in detoxification;
129=(h) describe and explain the production of urine, with reference to the processes of ultrafiltration and selective reabsorption;
132=(k) describe how urine samples can be used to test for pregnancy and detect misuse of anabolic steroids (HSW6a, 6b).
147=(o) describe the effect on the rate of photosynthesis, and on levels of GP, RuBP and TP, of changing carbon dioxide concentration, light intensity and temperature;
149=(q) describe how to investigate experimentally the factors that affect the rate of photosynthesis (HSW3).
103=(b) describe, with the aid of diagrams, the structure and functions of sensory and motor neurones;
110=(i) describe, with the aid of diagrams, the structure of a cholinergic synapse;
116=(d) describe, with the aid of diagrams and photographs, the histology of the pancreas, and outline its role as an endocrine and exocrine gland;
124=(c) describe, with the aid of diagrams and photographs, the histology and gross structure of the liver;
127=(f) describe, with the aid of diagrams and photographs, the histology and gross structure of the kidney;
128=(g) describe, with the aid of diagrams and photographs, the detailed structure of a nephron and its associated blood vessels;
151=(b) describe, with the aid of diagrams, the structure of ATP;
130=(i) explain, using water potential terminology, the control of the water content of the blood, with reference to the roles of the kidney, osmoreceptors in the hypothalamus and the posterior pituitary gland;
137=(e) explain, with the aid of diagrams and electron micrographs, how the structure of chloroplasts enables them to carry out their functions;
157=(h) explain, with the aid of diagrams and electron micrographs, how the structure of mitochondria enables them to carry out their functions;
109=(h) compare and contrast the structure and function of myelinated and non-myelinated neurones;
119=(g) compare and contrast the causes of Type 1 (insulin-dependent) and Type 2 (non-insulin-dependent) diabetes mellitus;
170=(u) compare and contrast anaerobic respiration in mammals and in yeast;
97=(b) state that cells need to communicate with each other by a process called cell signalling;
98=(c) state that neuronal and hormonal systems are examples of cell signalling;
134=(b) state that light energy is used during photosynthesis to produce complex organic molecules;
136=(d) state that in plants photosynthesis is a two-stage process taking place in chloroplasts;
140=(h) state that the light-dependent stage takes place in thylakoid membranes and that the light-independent stage takes place in the stroma;
145=(m) state that TP can be used to make carbohydrates, lipids and amino acids;
146=(n) state that most TP is recycled to RuBP;
152=(c) state that ATP provides the immediate source of energy for biological processes;
154=(e) state that glycolysis takes place in the cytoplasm;
156=(g) state that, during aerobic respiration in animals, pyruvate is actively transported into mitochondria;
158=(i) state that the link reaction takes place in the mitochondrial matrix;
161=(l) state that the Krebs cycle takes place in the mitochondrial matrix;
166=(q) state that oxygen is the final electron acceptor in aerobic respiration;
91=(c) explain the benefits for agriculture of maintaining the biodiversity of animal and plant species (HSW6a, 6b, 7c);
100=(e) explain the principles of homeostasis in terms of receptors, effectors and negative feedback;
114=(b) explain the meaning of the terms first messenger and second messenger, with reference to adrenaline and cyclic AMP (cAMP);
117=(e) explain how blood glucose concentration is regulated, with reference to insulin, glucagon and the liver;
123=(b) explain the importance of removing metabolic wastes, including carbon dioxide and nitrogenous waste, from the body;
135=(c) explain how respiration in plants and animals depends upon the products of photosynthesis;
139=(g) explain the importance of photosynthetic pigments in photosynthesis;
142=(j) explain the role of water in the light-dependent stage;
144=(l) explain the role of carbon dioxide in the light-independent stage (Calvin cycle);
153=(d) explain the importance of coenzymes in respiration, with reference to NAD and coenzyme A;
160=(k) explain that acetate is combined with coenzyme A to be carried to the next stage;
163=(n) explain that during the Krebs cycle, decarboxylation and dehydrogenation occur, NAD and FAD are reduced and substrate level phosphorylation occurs;
168=(s) explain why the theoretical maximum yield of ATP per molecule of glucose is rarely, if ever, achieved in aerobic respiration;
169=(t) explain why anaerobic respiration produces a much lower yield of ATP than aerobic respiration;
172=(w) explain the difference in relative energy values of carbohydrate, lipid and protein respiratory substrates.
[F215]
188=(f) describe the interactions between loci (epistasis). (Production of genetic diagrams is not required);
191=(i) describe the differences between continuous and discontinuous variation;
201=(s) describe how artificial selection has been used to produce the modern dairy cow and to produce bread wheat (Triticum aestivum) (HSW6a, 6b).
203=(b) describe the production of natural clones in plants using the example of vegetative propagation in elm trees;
204=(c) describe the production of artificial clones of plants from tissue culture;
206=(e) describe how artificial clones of animals can be produced;
211=(d) describe how enzymes can be immobilised;
214=(g) describe the differences between primary and secondary metabolites;
221=(e) describe how sections of DNA containing a desired gene can be extracted from a donor organism using restriction enzymes;
223=(g) describe how DNA probes can be used to identify fragments containing specific sequences;
228=(l) describe the advantage to microorganisms of the capacity to take up plasmid DNA from the environment;
240=(e) describe how energy is transferred though ecosystems;
244=(i) describe one example of primary succession resulting in a climax community;
245=(j) describe how the distribution and abundance of organisms can be measured, using line transects, belt transects, quadrats and point quadrats (HSW3);
246=(k) describe the role of decomposers in the decomposition of organic material;
247=(l) describe how microorganisms recycle nitrogen within ecosystems. (Only Nitrosomonas, Nitrobacter and Rhizobium need to be identified by name).
250=(c) describe predator-prey relationships and their possible effects on the population sizes of both the predator and the prey;
262=(f) describe how plant hormones are used commercially (HSW6a).
267=(e) describe the role of the brain and nervous system in the co-ordination of muscular movement;
268=(f) describe how co-ordinated movement requires the action of skeletal muscles about joints, with reference to the movement of the elbow joint;
276=(b) describe escape reflexes, taxes and kineses as examples of genetically-determined innate behaviours;
278=(d) describe habituation, imprinting, classical and operant conditioning, latent and insight learning as examples of learned behaviours;
175=(c) describe, with the aid of diagrams, the way in which a nucleotide sequence codes for the amino acid sequence in a polypeptide;
176=(d) describe, with the aid of diagrams, how the sequence of nucleotides within a gene is used to construct a polypeptide, including the roles of messenger RNA, transfer RNA and ribosomes;
183=(a) describe, with the aid of diagrams and photographs, the behaviour of chromosomes during meiosis, and the associated behaviour of the nuclear envelope, cell membrane and centrioles. (Names of the main stages are expected, but not the subdivisions of prophase);
210=(c) describe, with the aid of diagrams, and explain the standard growth curve of a microorganism in a closed culture;
266=(d) describe, with the aid of diagrams, the gross structure of the human brain, and outline the functions of the cerebrum, cerebellum, medulla oblongata and hypothalamus;
279=(e) describe, using one example, the advantages of social behaviour in primates;
196=(n) explain, with examples, how environmental factors can act as stabilising or evolutionary forces of natural selection;
251=(d) explain, with examples, the terms interspecific and intraspecific competition;
269=(g) explain, with the aid of diagrams and photographs, the sliding filament model of muscular contraction;
200=(r) compare and contrast natural selection and artificial selection;
213=(f) compare and contrast the processes of continuous culture and batch culture;
271=(i) compare and contrast the action of synapses and neuromuscular junctions;
173=(a) state that genes code for polypeptides, including enzymes;
177=(e) state that mutations cause changes to the sequence of nucleotides in DNA molecules;
179=(g) state that cyclic AMP activates proteins by altering their three-dimensional structure;
208=(a) state that biotechnology is the industrial use of living organisms (or parts of living organisms) to produce food, drugs or other products (HSW6a);
226=(j) state other vectors into which fragments of DNA may be incorporated;
237=(b) state that ecosystems are dynamic systems;
273=(k) state that responses to environmental stimuli in mammals are co-ordinated by nervous and endocrine systems;
174=(b) explain the meaning of the term genetic code;
178=(f) explain how mutations can have beneficial, neutral or harmful effects on the way a protein functions;
180=(h) explain genetic control of protein production in a prokaryote using the lac operon;
181=(i) explain that the genes that control development of body plans are similar in plants, animals and fungi, with reference to homeobox sequences (HSW1);
184=(b) explain the terms allele, locus, phenotype, genotype, dominant, codominant and recessive;
185=(c) explain the terms linkage and crossing-over;
186=(d) explain how meiosis and fertilisation can lead to variation through the independent assortment of alleles;
192=(j) explain the basis of continuous and discontinuous variation by reference to the number of genes which influence the variation;
193=(k) explain that both genotype and environment contribute to phenotypic variation. (No calculations of heritability will be expected);
194=(l) explain why variation is essential in selection;
197=(o) explain how genetic drift can cause large changes in small populations;
198=(p) explain the role of isolating mechanisms in the evolution of new species, with reference to ecological (geographic), seasonal (temporal) and reproductive mechanisms;
199=(q) explain the significance of the various concepts of the species, with reference to the biological species concept and the phylogenetic (cladistic/evolutionary) species concept (HSW1);
209=(b) explain why microorganisms are often used in biotechnological processes;
212=(e) explain why immobilised enzymes are used in large-scale production;
215=(h) explain the importance of manipulating the growing conditions in a fermentation vessel in order to maximise the yield of product required;
216=(i) explain the importance of asepsis in the manipulation of microorganisms.
220=(d) explain that genetic engineering involves the extraction of genes from one organism, or the manufacture of genes, in order to place them in another organism (often of a different species) such that the receiving organism expresses the gene product (HSW6a);
225=(i) explain how isolated DNA fragments can be placed in plasmids, with reference to the role of ligase;
227=(k) explain how plasmids may be taken up by bacterial cells in order to produce a transgenic microorganism that can express a desired gene product;
233=(q) explain the term gene therapy;
234=(r) explain the differences between somatic cell gene therapy and germ line cell gene therapy;
243=(h) explain how human activities can manipulate the flow of energy through ecosystems (HSW6b);
248=(a) explain the significance of limiting factors in determining the final size of a population;
249=(b) explain the meaning of the term carrying capacity;
253=(f) explain how the management of an ecosystem can provide resources in a sustainable way, with reference to timber production in a temperate country;
254=(g) explain that conservation is a dynamic process involving management and reclamation;
257=(a) explain why plants need to respond to their environment in terms of the need to avoid predation and abiotic stress;
259=(c) explain how plant responses to environmental changes are co-ordinated by hormones, with reference to responding to changes in light direction;
274=(l) explain how, in mammals, the "fight or flight" response to environmental stimuli is co-ordinated by the nervous and endocrine systems.
275=(a) explain the advantages to organisms of innate behaviour;
277=(c) explain the meaning of the term learned behaviour;
256=(i) outline, with examples, the effects of human activities on the animal and plant populations in the Galapagos Islands (HSW6b).
182=(j) outline how apoptosis (programmed cell death) can act as a mechanism to change body plans.
202=(a) outline the differences between reproductive and non-reproductive cloning;
217=(a) outline the steps involved in sequencing the genome of an organism;
218=(b) outline how gene sequencing allows for genome-wide comparisons between individuals and between species (HSW7b);
222=(f) outline how DNA fragments can be separated by size using electrophoresis (HSW3);
224=(h) outline how the polymerase chain reaction (PCR) can be used to make multiple copies of DNA fragments;
229=(m) outline how genetic markers in plasmids can be used to identify the bacteria that have taken up a recombinant plasmid;
230=(n) outline the process involved in the genetic engineering of bacteria to produce human insulin;
231=(o) outline the process involved in the genetic engineering of "Golden Rice"^TM (HSW6a);
232=(p) outline how animals can be genetically engineered for xenotransplantation (HSW6a, 6b);
241=(f) outline how energy transfers between trophic levels can be measured;
261=(e) outline the role of hormones in leaf loss in deciduous plants;
264=(b) outline the organisation of the nervous system in terms of central and peripheral systems in humans;
265=(c) outline the organisation and roles of the autonomic nervous system;
270=(h) outline the role of ATP in muscular contraction, and how the supply of ATP is maintained in muscles;
272=(j) outline the structural and functional differences between voluntary, involuntary and cardiac muscle;
219=(c) define the term recombinant DNA;
236=(a) define the term ecosystem;
238=(c) define the terms biotic factor and abiotic factor, using named examples;
239=(d) define the terms producer, consumer decomposer and trophic level;
258=(b) define the term tropism;
205=(d) discuss the advantages and disadvantages of plant cloning in agriculture (HSW6a, 6b, 7c);
207=(f) discuss the advantages and disadvantages of cloning animals (HSW4, 6a, 6b, 7c).
235=(s) discuss the ethical concerns raised by the genetic manipulation of animals (including humans), plants and microorganisms (HSW4, 6a, 6b, 7c).
242=(g) discuss the efficiency of energy transfers between trophic levels;
255=(h) discuss the economic, social and ethical reasons for conservation of biological resources (HSW6b, 7c);
263=(a) discuss why animals need to respond to their environment;
280=(f) discuss how the links between a range of human behaviours and the dopamine receptor DRD4 may contribute to the understanding of human behaviour (HSW7a);
260=(d) evaluate the experimental evidence for the role of auxins in the control of apical dominance and gibberellin in the control of stem elongation;
187=(e) use genetic diagrams to solve problems involving sex linkage and codominance;
190=(h) use the chi-squared (?2) test to test the significance of the difference between observed and expected results. (The formula for the chi-squared test will be provided);
195=(m) use the Hardy-Weinberg principle to calculate allele frequencies in populations (HSW1);
189=(g) predict phenotypic ratios in problems involving epistasis;
252=(e) distinguish between the terms conservation and preservation (HSW6a, 6b);